#ifndef WINDOWUTILS_H
#define WINDOWUTILS_H

#include <windows.h>
#include "HWNDStack.h"

#define CFG_MENU_ITEM_START 0x4740
#define MENU_ITEM_OPACITY_10 CFG_MENU_ITEM_START
#define MENU_ITEM_OPACITY_20 MENU_ITEM_OPACITY_10+1
#define MENU_ITEM_OPACITY_30 MENU_ITEM_OPACITY_20+1
#define MENU_ITEM_OPACITY_40 MENU_ITEM_OPACITY_30+1
#define MENU_ITEM_OPACITY_50 MENU_ITEM_OPACITY_40+1
#define MENU_ITEM_OPACITY_60 MENU_ITEM_OPACITY_50+1
#define MENU_ITEM_OPACITY_70 MENU_ITEM_OPACITY_60+1
#define MENU_ITEM_OPACITY_80 MENU_ITEM_OPACITY_70+1
#define MENU_ITEM_OPACITY_90 MENU_ITEM_OPACITY_80+1
#define MENU_ITEM_OPACITY_100 MENU_ITEM_OPACITY_90+1


#define MENU_ITEM_OPACITY_DEFAULT_10 MENU_ITEM_OPACITY_100+1
#define MENU_ITEM_OPACITY_DEFAULT_20 MENU_ITEM_OPACITY_DEFAULT_10+1
#define MENU_ITEM_OPACITY_DEFAULT_30 MENU_ITEM_OPACITY_DEFAULT_20+1
#define MENU_ITEM_OPACITY_DEFAULT_40 MENU_ITEM_OPACITY_DEFAULT_30+1
#define MENU_ITEM_OPACITY_DEFAULT_50 MENU_ITEM_OPACITY_DEFAULT_40+1
#define MENU_ITEM_OPACITY_DEFAULT_60 MENU_ITEM_OPACITY_DEFAULT_50+1
#define MENU_ITEM_OPACITY_DEFAULT_70 MENU_ITEM_OPACITY_DEFAULT_60+1
#define MENU_ITEM_OPACITY_DEFAULT_80 MENU_ITEM_OPACITY_DEFAULT_70+1
#define MENU_ITEM_OPACITY_DEFAULT_90 MENU_ITEM_OPACITY_DEFAULT_80+1
#define MENU_ITEM_OPACITY_DEFAULT_100 MENU_ITEM_OPACITY_DEFAULT_90+1

HWND GetNextVisibleWindow(HWND hwnd);
void SetWindowOpacity(HWND handle, unsigned int percents);
void SetWindowCustomMenu(HWND hwnd);
void SetWindowEXTTransparent(HWNDStack* hSTarget, int state);

#endif // WINDOWUTILS_H
